name: Modal – Deploy WAN API
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Modal CLI
        run: pip install --upgrade modal

      - name: Auth to Modal
        run: |
          modal token set --token-id "$MODAL_TOKEN_ID" --token-secret "$MODAL_TOKEN_SECRET" --no-verify
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}

      - name: Deploy ASGI endpoint on GPU
        run: |
          WAN_MODEL_ID="Wan-AI/Wan2.1-T2V-1.3B-Diffusers" modal deploy modal_app/02_wan_api.py
